### ISSUE TITLE
Conversion to directory tree loses certain Drag and Drop parameters

### ISSUE THREAD

**Issue by RNLFoof** [Medo42/Gmk-Splitter#9]
I feel pretty silly submitting an issue on a project whose last code change was ten years ago. I won't be offended by a response to the effect of "What? Go away"

Anyway, I ran these commands, using the V0.17 jar:
![image](https://user-images.githubusercontent.com/24951381/181143071-aea168ad-ee5e-4f58-b018-e641e6897292.png)

and here's some examples of original gm81 -> xml(with argument missing) -> gm81 created from directory tree
![image](https://user-images.githubusercontent.com/24951381/181144400-98805de7-0bed-4a08-af76-205c4f748efc.png)
![image](https://user-images.githubusercontent.com/24951381/181144669-1cee5da5-bf60-4869-b58a-573cf6e1af29.png)
![image](https://user-images.githubusercontent.com/24951381/181144822-1239cb93-c2d3-47db-af70-30fd3db12d37.png)
![image](https://user-images.githubusercontent.com/24951381/181145010-70103c4e-f58d-45dc-ad3e-c1f2e3867ff1.png)

**Comment by Medo42** [comment]
Hi. Nah, it's nice to see someone outside of the Gang Garrison 2 project
still has a use for this.

Can you attach a .gm81 file with these failing examples?

Am Mi., 27. Juli 2022 um 04:29 Uhr schrieb RNLFoof ***@***.***

**Comment by RNLFoof** [comment]
Hi, and wow, thank you for the quick reply. Good to hear, also.

Here:
[et5.zip](https://github.com/Medo42/Gmk-Splitter/files/9201175/et5.zip)

**Comment by Medo42** [comment]
The good news is that the fix was simple, the bad news that I was too lazy to set up the project properly, and I didn't want to mess things up by building against the wrong version of LateralGM either, so I just edited the existing .jar file.
Can you give it a try and see if it works now? For some reason I got an error when trying to split your file here I get error messages about duplicate resource names.

[GmkSplitter.v0.18.zip](https://github.com/Medo42/Gmk-Splitter/files/9203279/GmkSplitter.v0.18.zip)

**Comment by RNLFoof** [comment]
Oh, you're getting that error because I'm dumb and sent you the wrong file. Sorry about that. Here, this one should be correct, if you need it for some reason:
[et5.zip](https://github.com/Medo42/Gmk-Splitter/files/9203598/et5.zip)

Anyway, seems to work! Thanks a lot for your help!
